#--------------------------------
# GitHub Action Part-1 Basics
#
# Copyleft (c) by alexxx09097
#--------------------------------
name: My-GitHub-Action-Basics

on:
  push:
    branches: 
    - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run : echo "Hello world from Testing job"
    

  my_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run : echo "Hello world from Deploy job"
